name: Index help center pages

on:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Index help center pages
      run: |
        make index-helpcenter
      env:
        ES_URL: ${{ secrets.ES_URL }}
